@url_dev=http://localhost:3055/v1/api

### refreshToken

PATCH {{url_dev}}/shop/refreshToken
Content-Type: application/json
x-api-key: 2b8070c503ebfc2a030908a5d793c68c4dd59d33b20fe1d5ce0c82c84e54f86bad534069981697e7693aa0453081a519b3d32a00e34ca2a61deca7e4475c2aa4
x-client-id: 6608fd3e14fb41350c0b1fab
x-refresh-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjA4ZmQzZTE0ZmI0MTM1MGMwYjFmYWIiLCJlbWFpbCI6InNob3B0ZXN0MDAwMEBnbWFpbC5jb20iLCJpYXQiOjE3MTIwODA0NTIsImV4cCI6MTcxMjY4NTI1Mn0.ChgilC6tn9TzF87rYNr3GGUOWkIiD2msr9oiMMb4VWPUB9kYf6RLX9PFc268aOhYj8Z3qMYrXoI0j8MRpKBXhql4PU8kgTDYrGoQBlJyMC0fInRVPH2ZXwffgdbb-RKXujnXbb5dW2BYSdp-AQukFwab0KpXBJEl5KNIAVwGSEEomVCjW0daiRAdmyUyUkuaDCEWP0MUHJL3fy4wdYcaXfxhTypz0dTp4GEp3wXRHHEiDqDv3Z_Wc6oEu-Qpzx-uEMC2qXACMnhXtlR4S2RpaV-YMWSm4vhW2dHI7Y82qfTYE4eJdKWrppbIo76L0AkesRY5xg56BCY-oWXs8LKJevw51Vs1cHyY6rOMAS8McS4CslfKrboBxgZ-X4iQPmK1INgt2_saGmSdQgXWkJmP-Ehd-8M2iFExkEYkS-ik_rZptTpJSvOasRhwDP1mnuGgOXhJrotKHgzkcOpmXfqUXMtaYJgmC1D_OzvvDJSfnc3wOCTjvXedY0PWFAX-WrBNwWyGZbOEnA1xEdP52spch3S2w7QbKDVAOZ13Q59Sw3e7b1gL2XxuUl6PBJghB0wHLMqJgFYNM4lf8y18-_xfysQvesNfD3TdLkoF7entVN-lIZrZlj9GQXSXKQH6f8K5hWeErYk4UxOhiflbas7TJkLs9ME84Q-L74akcQ7T6Gk


### logout
DELETE {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: 2b8070c503ebfc2a030908a5d793c68c4dd59d33b20fe1d5ce0c82c84e54f86bad534069981697e7693aa0453081a519b3d32a00e34ca2a61deca7e4475c2aa4
x-client-id: 6608fd3e14fb41350c0b1fab
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjA4ZmQzZTE0ZmI0MTM1MGMwYjFmYWIiLCJlbWFpbCI6InNob3B0ZXN0MDAwMEBnbWFpbC5jb20iLCJpYXQiOjE3MTIwODAxODksImV4cCI6MTcxMjI1Mjk4OX0.ePhT8FdPBNus-hePabicaK9-2ZILZEyFxsNhobcCgidkRix_F0J9OZOt_PV1qldFce4l00OYR1hxweDzhLJTy_foZEMmVPOErfDO_wqSwNtp42d8oktCm5KtHynvPTHu_PtCJO5Qm2Kou6r8Nils8N0XnJnBSnLj7PTAjUri_XbYYuApiOzRjrCG0aBo3RCZjLzU8MjRoyBu63MZbCNFHF71LeoAtrFEBO1T9nId-HEGYc6dL8TQlPOwDR_yUtaUATLV-USsv3E0eYphhTXG1FqHHrTtKdDNMDyEiGWqyqbzrwfT-ZNIr5ZRZ-dZM9fFJaFpaBkJThr2mGGvvDo8Jk22Zoj7HbmAJmfo2TBHBojpkuehqUM4tbSzlnwtFl2b3diPnJRLme3P4gqycQs4jYGLNKgGWDmiZaRPkEQw7OUaDbURoZIzThnixnJ1yps69X-39xj-PFiFbyrDoXzESPtGyIhnsucMwri0yZdwYLmQW4jMlbTqqm2V4kzUTvxtEIbTgsrgSofBXwwN-ol3fcDw948gGKJw85pSgCUqIkiNt8hAcG2LSZAf4yE9ap0qL-P9zjuF4v96S0rk2Ef3lbiuQwlsBGgLcfAoft2_PY_M2aPxMQV4g7jXmupB_h6jB810z6jrmuU3HrdaNYYTyWsT1_Q00TzPbcsokfY_snQ

### login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: 2b8070c503ebfc2a030908a5d793c68c4dd59d33b20fe1d5ce0c82c84e54f86bad534069981697e7693aa0453081a519b3d32a00e34ca2a61deca7e4475c2aa4

{
    "email": "shoptest0000@gmail.com",
    "password": "test1234@"
}


### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 2b8070c503ebfc2a030908a5d793c68c4dd59d33b20fe1d5ce0c82c84e54f86bad534069981697e7693aa0453081a519b3d32a00e34ca2a61deca7e4475c2aa4

{
    "name": "Shop Test",
    "email": "shoptest0000@gmail.com",
    "password": "test1234@"
}

